//! Per-file diagnostics, generated by the shared `axiom-check` functions and
//! enriched with byte spans from the position layer.
//!
//! The check functions are reused verbatim — this module never re-implements
//! parsing, type checking, or resolution. It only *attributes* spans to
//! diagnostics that the CLI does not need but editors do.

use std::path::Path;

use axiom_check::{check_models, check_queries, check_schemas};
use axiom_diagnostics::{Diagnostic, Span};

use crate::database::{AnalysisDatabase, Lang, Role};
use crate::symbols::Span as ByteSpan;
use crate::token::PositionIndex;

impl AnalysisDatabase {
    /// Diagnostics for every file in the workspace.
    pub fn all_diagnostics(&mut self) -> Vec<Diagnostic> {
        let schema = self.schema_diags();
        let query = self.query_diags();
        let model = self.model_diags();
        schema.into_iter().chain(query).chain(model).collect()
    }

    /// Diagnostics for a single file, recomputed incrementally.
    pub fn file_diagnostics(&mut self, path: &Path) -> Vec<Diagnostic> {
        let mut diags = Vec::new();
        match self.file_role(path) {
            Role::Schema => {
                diags.extend(
                    self.schema_diags()
                        .into_iter()
                        .filter(|d| d.file.as_path() == path),
                );
            }
            Role::Query => {
                diags.extend(
                    self.query_diags()
                        .into_iter()
                        .filter(|d| d.file.as_path() == path),
                );
            }
            Role::Model => {
                diags.extend(
                    self.model_diags()
                        .into_iter()
                        .filter(|d| d.file.as_path() == path),
                );
            }
            Role::Unknown => {
                if let Some(text) = self.file_text(path) {
                    match self.file_lang(path) {
                        Some(Lang::Sql) => {
                            if let Err(err) = axiom_core::catalog::parse_sql_catalog(text) {
                                diags.push(axiom_check::diagnostics::parse_error(path, "check.sql-parse", err.to_string()));
                            }
                        }
                        Some(Lang::Axm) => {
                            if let Err(err) = axiom_core::axm::parser::parse_axm_file(text) {
                                diags.push(axiom_check::diagnostics::parse_error(path, "check.axm-parse", err.to_string()));
                            }
                        }
                        None => {}
                    }
                }
            }
        }

        let (text, index) = match self.file_data(path) {
            Some((_, text, index)) => (text.to_string(), index.clone()),
            None => (String::new(), PositionIndex::new_sql("")),
        };
        diags
            .into_iter()
            .map(|d| enrich(path, &text, &index, d))
            .collect()
    }

    fn schema_diags(&mut self) -> Vec<Diagnostic> {
        let schema_files = self.role_files(Role::Schema);
        if schema_files.is_empty() {
            return Vec::new();
        }
        let (_, diags) = check_schemas(&schema_files);
        diags
    }

    fn query_diags(&mut self) -> Vec<Diagnostic> {
        if !self.query_diags_dirty {
            return self.query_diags.clone().unwrap_or_default();
        }
        let schema_files = self.role_files(Role::Schema);
        let query_files = self.role_files(Role::Query);
        let model_files = self.role_files(Role::Model);
        let diags = if query_files.is_empty() {
            Vec::new()
        } else {
            let schema_hash = axiom_check::workspace::aggregate_hash(&schema_files);
            let declared = axiom_check::collect_declared_models(&model_files);
            let catalog = self.catalog().clone();
            let (_, diags) = check_queries(
                self.tools.as_mut(),
                &schema_hash,
                &catalog,
                &declared,
                &query_files,
            );
            diags
        };
        self.query_diags = Some(diags.clone());
        self.query_diags_dirty = false;
        diags
    }

    fn model_diags(&mut self) -> Vec<Diagnostic> {
        if !self.model_diags_dirty {
            return self.model_diags.clone().unwrap_or_default();
        }
        let model_files = self.role_files(Role::Model);
        let diags = if model_files.is_empty() {
            Vec::new()
        } else {
            let (_, diags) = check_models(self.tools.as_mut(), &model_files);
            diags
        };
        self.model_diags = Some(diags.clone());
        self.model_diags_dirty = false;
        diags
    }

    fn role_files(&self, role: Role) -> Vec<(std::path::PathBuf, String)> {
        self.files
            .iter()
            .filter(|f| f.role == role)
            .map(|f| (f.path.clone(), f.text.clone()))
            .collect()
    }
}/// Attach a byte span to a diagnostic that the compiler produced without one.
fn enrich(path: &Path, text: &str, index: &PositionIndex, mut diag: Diagnostic) -> Diagnostic {
    if diag.span.is_some() {
        return diag;
    }
    let span = span_for_diagnostic(text, index, &diag);
    diag.span = Some(Span::new(span.start, span.end));
    let _ = path;
    diag
}

fn span_for_diagnostic(text: &str, index: &PositionIndex, diag: &Diagnostic) -> ByteSpan {
    if let Some(name) = name_from_message(&diag.code, &diag.message)
        && let Some(token) = index.find_word_any(&name)
    {
        return ByteSpan::new(token.start, token.end);
    }
    // Fall back to the first significant token, then to offset zero.
    if let Some(token) = index.tokens.iter().find(|t| !t.text.is_empty()) {
        ByteSpan::new(token.start, token.end)
    } else {
        ByteSpan::new(0, text.len().min(1))
    }
}

fn name_from_message(code: &str, message: &str) -> Option<String> {
    let marker = match code {
        "check.missing-table" => "table `",
        "check.missing-column" => "column `",
        "check.query-return-type" => "returns `",
        "check.regex-invalid" => "on `",
        "check.duplicate-model" => "model `",
        _ => "`",
    };
    if marker.is_empty() {
        return None;
    }
    let start = message.find(marker)? + marker.len();
    let relative = &message[start..];
    let end = relative.find('`')?;
    let name = relative[..end].trim();
    if name.is_empty() {
        None
    } else {
        Some(name.to_string())
    }
}
