//! TypeScript code generation.

use std::fmt::Write;

use crate::catalog::{ColumnSchema, RuleKind, TableCatalog, TableSchema, ValidationRule};
use crate::codegen::util;

const PRESETS: &[(&str, &str, &str, &str)] = &[
    (
        "EMAIL",
        "email",
        "^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$",
        "i",
    ),
    (
        "URL",
        "url",
        "^(https?://)?([\\da-z.-]+)\\.([a-z.]{2,6})([/\\w .-]*)*/?$",
        "i",
    ),
    (
        "UUID",
        "uuid",
        "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$",
        "",
    ),
    (
        "ULID",
        "ulid",
        "^[0-9A-HJKMNP-TV-Z]{26}$",
        "",
    ),
    (
        "IPV4",
        "ipv4",
        "^((25[0-5]|2[0-4][0-9]|1[0-9]{2}|[1-9]?[0-9])\\.){3}(25[0-5]|2[0-4][0-9]|1[0-9]{2}|[1-9]?[0-9])$",
        "",
    ),
    (
        "IPV6",
        "ipv6",
        "^(([0-9a-fA-F]{1,4}:){7}[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,7}:|([0-9a-fA-F]{1,4}:){1,6}:[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,5}(:[0-9a-fA-F]{1,4}){1,2}|([0-9a-fA-F]{1,4}:){1,4}(:[0-9a-fA-F]{1,4}){1,3}|([0-9a-fA-F]{1,4}:){1,3}(:[0-9a-fA-F]{1,4}){1,4}|([0-9a-fA-F]{1,4}:){1,2}(:[0-9a-fA-F]{1,4}){1,5}|[0-9a-fA-F]{1,4}:((:[0-9a-fA-F]{1,4}){1,6})|:((:[0-9a-fA-F]{1,4}){1,7}|:)|fe80:(:[0-9a-fA-F]{0,4}){0,4}%[0-9a-zA-Z]{1,}|::(ffff(:0{1,4}){0,1}:){0,1}((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])\\.){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])|([0-9a-fA-F]{1,4}:){1,4}:((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])\\.){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9]))$",
        "",
    ),
    (
        "ISO_DATE",
        "iso_date",
        "^\\d{4}-\\d{2}-\\d{2}$",
        "",
    ),
    (
        "ALPHANUMERIC",
        "alphanumeric",
        "^[a-zA-Z0-9]+$",
        "",
    ),
];

/// Generate a TypeScript module describing the catalog tables and their
/// validators.
pub fn generate_typescript(catalog: &TableCatalog) -> String {
    let mut out = String::new();
    out.push_str("// Generated by axiom. Do not edit.\n\n");
    out.push_str("export interface ValidationError {\n");
    out.push_str("  path: string;\n");
    out.push_str("  message: string;\n");
    out.push_str("}\n\n");

    for table in &catalog.tables {
        emit_table(&mut out, table);
    }

    for (const_name, preset_name, pattern, flags) in PRESETS {
        if preset_used(catalog, preset_name) {
            let _ = writeln!(
                out,
                "const {const_name}_RE = {};",
                util::ts_regex_literal(pattern, flags)
            );
        }
    }

    out
}

fn emit_table(out: &mut String, table: &TableSchema) {
    let type_name = util::type_name(table);

    let _ = writeln!(out, "export interface {type_name} {{");
    for column in &table.columns {
        let field = util::ts_field_name(&column.name);
        let ty = util::ts_type(&column.data_type);
        let nullable = if column.nullable { " | null" } else { "" };
        let _ = writeln!(out, "  {field}: {ty}{nullable};");
    }
    out.push_str("}\n\n");

    let _ = writeln!(
        out,
        "export function validate{type_name}(input: {type_name}): ValidationError[] {{"
    );
    out.push_str("  const errors: ValidationError[] = [];\n");
    for column in &table.columns {
        emit_column_validation(out, column);
    }
    out.push_str("  return errors;\n");
    out.push_str("}\n\n");
}

fn emit_column_validation(out: &mut String, column: &ColumnSchema) {
    let field = util::ts_field_name(&column.name);
    let transforms = util::ts_transform_chain(column);
    let validations: Vec<&ValidationRule> = column
        .rules
        .iter()
        .filter(|rule| !util::is_transform(&rule.kind))
        .collect();

    if transforms.is_none() && validations.is_empty() {
        return;
    }

    let input = format!("input.{field}");
    let body_indent = if column.nullable { "    " } else { "  " };

    if column.nullable {
        let _ = writeln!(out, "  if ({input} != null) {{");
    }

    let value_expr = match &transforms {
        Some(chain) => {
            let _ = writeln!(out, "{body_indent}const {field} = {input}{chain};");
            field.clone()
        }
        None => input,
    };

    for rule in validations {
        let condition = ts_condition(&rule.kind, &value_expr);
        let message = util::escape_ts(&util::rule_message(rule));
        let _ = writeln!(out, "{body_indent}if (!({condition})) {{");
        let _ = writeln!(
            out,
            "{body_indent}  errors.push({{ path: \"{field}\", message: \"{message}\" }});"
        );
        let _ = writeln!(out, "{body_indent}}}");
    }

    if column.nullable {
        out.push_str("  }\n");
    }
}

fn ts_condition(kind: &RuleKind, value: &str) -> String {
    match kind {
        RuleKind::Email => format!("EMAIL_RE.test({value})"),
        RuleKind::Url => format!("URL_RE.test({value})"),
        RuleKind::Uuid => format!("UUID_RE.test({value})"),
        RuleKind::Ulid => format!("ULID_RE.test({value})"),
        RuleKind::Ipv4 => format!("IPV4_RE.test({value})"),
        RuleKind::Ipv6 => format!("IPV6_RE.test({value})"),
        RuleKind::IsoDate => format!("ISO_DATE_RE.test({value})"),
        RuleKind::Alphanumeric => format!("ALPHANUMERIC_RE.test({value})"),
        RuleKind::MinLen(n) => format!("{value}.length >= {n}"),
        RuleKind::MaxLen(n) => format!("{value}.length <= {n}"),
        RuleKind::Min(n) => format!("{value} >= {n}"),
        RuleKind::Max(n) => format!("{value} <= {n}"),
        RuleKind::Regex(pattern) => {
            let literal = util::ts_regex_literal(pattern, "");
            format!("{literal}.test({value})")
        }
        RuleKind::Trim | RuleKind::LowerCase | RuleKind::UpperCase => String::new(),
    }
}

fn preset_used(catalog: &TableCatalog, preset: &str) -> bool {
    catalog.tables.iter().any(|table| {
        table.columns.iter().any(|column| {
            column
                .rules
                .iter()
                .any(|rule| preset_kind(&rule.kind) == Some(preset))
        })
    })
}

fn preset_kind(kind: &RuleKind) -> Option<&'static str> {
    match kind {
        RuleKind::Email => Some("email"),
        RuleKind::Url => Some("url"),
        RuleKind::Uuid => Some("uuid"),
        RuleKind::Ulid => Some("ulid"),
        RuleKind::Ipv4 => Some("ipv4"),
        RuleKind::Ipv6 => Some("ipv6"),
        RuleKind::IsoDate => Some("iso_date"),
        RuleKind::Alphanumeric => Some("alphanumeric"),
        _ => None,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::catalog::{ColumnSchema, TableSchema, ValidationRule};
    use std::borrow::Cow;

    fn col(
        name: &'static str,
        data_type: &'static str,
        nullable: bool,
        rules: Vec<ValidationRule<'static>>,
    ) -> ColumnSchema<'static> {
        ColumnSchema {
            name: Cow::Borrowed(name),
            data_type: Cow::Borrowed(data_type),
            nullable,
            primary_key: false,
            rules,
        }
    }

    fn table(name: &'static str, columns: Vec<ColumnSchema<'static>>) -> TableSchema<'static> {
        TableSchema {
            name: Cow::Borrowed(name),
            columns,
        }
    }

    fn rule(kind: RuleKind<'static>, msg: Option<&'static str>) -> ValidationRule<'static> {
        ValidationRule {
            kind,
            custom_message: msg.map(Cow::Borrowed),
        }
    }

    fn catalog_with_one_table() -> TableCatalog<'static> {
        let t = table(
            "users",
            vec![
                col(
                    "email",
                    "VARCHAR(255)",
                    false,
                    vec![
                        rule(RuleKind::Email, Some("Bad Email")),
                        rule(RuleKind::MinLen(3), None),
                        rule(RuleKind::Trim, None),
                        rule(RuleKind::LowerCase, None),
                    ],
                ),
                col("id", "BIGSERIAL", false, vec![]),
            ],
        );
        TableCatalog { tables: vec![t] }
    }

    #[test]
    fn emits_interface_with_types() {
        let out = generate_typescript(&catalog_with_one_table());
        assert!(out.contains("export interface Users {"));
        assert!(out.contains("email: string;"));
        assert!(out.contains("id: number;"));
    }

    #[test]
    fn emits_validation_error_push() {
        let out = generate_typescript(&catalog_with_one_table());
        assert!(out.contains("errors.push({ path: \"email\", message: \"Bad Email\" });"));
        assert!(out.contains("EMAIL_RE.test(email)"));
    }

    #[test]
    fn emits_transforms_before_validation() {
        let out = generate_typescript(&catalog_with_one_table());
        assert!(out.contains("const email = input.email.trim().toLowerCase();"));
        assert!(out.contains("email.length >= 3"));
    }

    #[test]
    fn emits_preset_constants_only_when_used() {
        let out = generate_typescript(&catalog_with_one_table());
        assert!(out.contains("const EMAIL_RE ="));
        assert!(!out.contains("const IPV6_RE ="));
        assert!(!out.contains("const UUID_RE ="));
    }

    #[test]
    fn nullable_columns_are_guarded() {
        let t = table(
            "sessions",
            vec![col(
                "external_id",
                "UUID",
                true,
                vec![rule(RuleKind::Uuid, Some("Bad UUID"))],
            )],
        );
        let out = generate_typescript(&TableCatalog { tables: vec![t] });
        assert!(out.contains("if (input.externalId != null) {"));
        assert!(out.contains("UUID_RE.test(input.externalId)"));
    }

    #[test]
    fn handles_regex_rule_inline() {
        let t = table(
            "accounts",
            vec![col(
                "slug",
                "VARCHAR",
                false,
                vec![rule(RuleKind::Regex(Cow::Borrowed("^[a-z0-9-]+$")), None)],
            )],
        );
        let out = generate_typescript(&TableCatalog { tables: vec![t] });
        assert!(out.contains("/^[a-z0-9-]+$/.test(input.slug)"));
    }
}
